# docker-compose.yml

services:
  cpp-stacktrace-example-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: cpp-stacktrace-example
    volumes:
        - ./:/workspace
        - cpp-stacktrace-example-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

    healthcheck:
      test: ["CMD", "test", "!", "-f", "/entrypoint.py.lock"]
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 240s

volumes:
  cpp-stacktrace-example-dev-vsc: